const fs=require('fs'),vm=require('vm'),assert=require('assert');
function boot(file,progress){const store=progress?{nightingale20_memory_v1:JSON.stringify(progress)}:{};const nodes={};const c={document:{querySelector:k=>nodes[k]||(nodes[k]={value:k==='#kind'?'group':'',options:[{},{}],focus(){},addEventListener(){}})},localStorage:{getItem:k=>store[k]||null,setItem:(k,v)=>store[k]=v},window:{addEventListener(){}},confirm:()=>true,console};vm.createContext(c);vm.runInContext(fs.readFileSync(__dirname+'/'+file,'utf8'),c);return {run:s=>vm.runInContext(s,c),c,store};}
const old=boot('迁移测试_旧练习.js');old.run("for(const k of ['group','all']){document.querySelector('#kind').value=k;active=true;for(let i=0;i<35;i++){const x=decks[k][saved[k].records[0][1]];answer(i%8===0?'!':x.键)}active=false}");
const data=JSON.parse(old.run('JSON.stringify(saved)'));const updated=boot('迁移测试_新练习.js',data);const result=JSON.parse(updated.run('JSON.stringify(saved)'));
for(const k of ['group','all']){assert.deepStrictEqual(result[k].records.slice(0,-1),data[k].records);assert.deepStrictEqual(result[k].records.at(-1),[-1,data[k].records.length]);assert.equal(result[k].answers,data[k].answers);assert.equal(result[k].errors,data[k].errors);assert.equal(updated.run(`decks.${k}.at(-1).根`),'正');assert.equal(updated.run(`decks.${k}.at(-1).键`),'s');}
updated.c.legacy=JSON.stringify({format:'nightingale-root-practice',version:1,mode:'all',progress:data});const imported=JSON.parse(updated.run('JSON.stringify(parseProgress(legacy).progress)'));assert.deepStrictEqual(imported,result);
updated.c.current=updated.run('JSON.stringify(progressPackage())');assert(updated.run('parseProgress(current)'));
for(const mutate of [p=>p.progress.all.records[0]=null,p=>p.progress.group.signature='bad',p=>p.progress.all.records[0]=p.progress.all.records[1],p=>p.progress.group.errors=-1]){const p=JSON.parse(updated.c.legacy);mutate(p);updated.c.bad=JSON.stringify(p);assert.throws(()=>updated.run('parseProgress(bad)'));}
const restart=boot('迁移测试_新练习.js',result);assert.deepStrictEqual(JSON.parse(restart.run('JSON.stringify(saved)')),result);
updated.run("document.querySelector('#kind').value='group';active=true;answer(decks.group[saved.group.records[0][1]].键)");assert.equal(updated.run('saved.group.answers'),data.group.answers+1);
console.log('PASS: 149→150及403→404；旧题顺序/阶段/当前题/计数完整保留；正追加队尾；旧文件导入、新文件回读、重启幂等、拒绝坏数据、可继续作答。');
